# Generated by Django 3.2 on 2021-04-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping',
            field=models.BooleanField(default=True),
        ),
    ]
