# Generated by Django 3.2 on 2021-04-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shippingaddress_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ship',
            field=models.BooleanField(default=True),
        ),
    ]
