# Generated by Django 3.2 on 2021-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210429_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ship',
        ),
        migrations.AddField(
            model_name='product',
            name='ship',
            field=models.BooleanField(default=True),
        ),
    ]
