# Generated by Django 3.2 on 2021-05-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210430_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
    ]
