# Generated by Django 3.2 on 2021-05-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210505_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippingAddress',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order'),
        ),
    ]
