# Generated by Django 3.2 on 2021-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210505_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('MP', 'may photocopy'), ('BT', 'bang tuong tac'), ('PS', 'print scan'), ('MC', 'may chieu'), ('MH', 'man hinh ghep')], default='MP', max_length=20),
        ),
    ]
